version: "3"
services:
  mongo:
    image: "mongo:6.0-focal"
    ports:
      - "27001:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: "root"
      MONGO_INITDB_ROOT_PASSWORD: "mongo"
    volumes:
      - { type: "bind", source: "./mongo/data", target: "/data/db" }
  mongo-express:
    image: "mongo-express:latest"
    depends_on:
      - "mongo"
    ports:
      - "27002:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: "root"
      ME_CONFIG_MONGODB_ADMINPASSWORD: "mongo"
      ME_CONFIG_MONGODB_URL: "mongodb://root:mongo@mongo:27017/"
  ocaz-forwarder:
    build:
      dockerfile: "../ocaz-forwarder/Dockerfile"
      context: "../ocaz-sandbox"
    depends_on:
      - "mongo"
    ports:
      - "27003:8000"
    environment:
      OCAZ_MONGODB_URL: "mongodb://root:mongo@mongo:27017/ocaz?authSource=admin"
  ocaz-video-digester:
    build:
      dockerfile: "../ocaz-video-digester/Dockerfile"
      context: "../ocaz-sandbox"
    depends_on:
      - "mongo"
    ports:
      - "27004:8000"
    environment:
      OCAZ_MONGODB_URL: "mongodb://root:mongo@mongo:27017/ocaz?authSource=admin"
      CACHE_DIR: "/mnt/cache"
    volumes:
      - { type: "bind", source: "./cache/video-digester", target: "/mnt/cache" }
  ocaz-simple-browser:
    build: "../ocaz-simple-browser"
    depends_on:
      - "ocaz-forwarder"
      - "ocaz-video-digester"
      - "ocaz-finder"
    ports:
      - "27005:3000"
    environment:
      OCAZ_MONGODB_URL: "mongodb://root:mongo@mongo:27017/ocaz?authSource=admin"
  ocaz-finder:
    build: "../ocaz-finder"
    depends_on:
      - "mongo"
    ports:
      - "27006:8000"
    environment:
      OCAZ_MONGODB_URL: "mongodb://root:mongo@mongo:27017/ocaz?authSource=admin"
      QUERY_DIR: "/mnt/query"
    volumes:
      - { type: "bind", source: "./query", target: "/mnt/query" }
  ocaz-classifier-nsfw-opennsfw2:
    build: "../ocaz-classifier-nsfw-opennsfw2"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
              count: 1
    ports:
      - "27007:8000"
  ocaz-classifier-nsfw-gantman:
    build: "../ocaz-classifier-nsfw-gantman"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
              count: 1
    ports:
      - "27008:8000"
  sandbox:
    build: "../ocaz-sandbox"
    environment:
      OCAZ_MONGODB_URL: "mongodb://root:mongo@mongo:27017/ocaz?authSource=admin"
      OCAZ_CLASSIFIER_NSFW_OPENNSFW2_BASE_URL: "http://ocaz-classifier-nsfw-opennsfw2:8000"
    volumes:
      - { type: "bind", source: "../ocaz-sandbox", target: "/mnt/workspace" }
    working_dir: "/mnt/workspace"
    command: "bash"
